"use strict";

let start = document.getElementById("start");
let buttonFirst = document.getElementsByTagName("button")[0];
let buttonSecond = document.getElementsByTagName("button")[1];
let depositBtn = document.querySelector("#deposit-check");
let incomeFirst = document.querySelectorAll(".additional_income-item")[0];
let incomeSecond = document.querySelectorAll(".additional_income-item")[1];
let budgetDay = document.getElementsByClassName("budget_day-value")[0];
let expensesMonth = document.getElementsByClassName("expenses_month-value")[0];
let addIncom = document.getElementsByClassName("additional_income-value")[0];
let addExpenses = document.getElementsByClassName("additional_expenses-value")[0];
let incomePeriod = document.getElementsByClassName("income_period-value")[0];
let targetMonth = document.getElementsByClassName("target_month-value")[0];
let range = document.querySelector(".period-select");
let salary = document.querySelector(".salary-amount");
let incomeTitle = document.querySelector(".income input.income-title");
let incomeAmount = document.querySelector(".income-amount");
let expensesTitle = document.querySelector(".expenses input.expenses-title");
let expensesAmount = document.querySelector(".expenses-amount");
let expensesItem = document.querySelector(".additional_expenses-item");
let mission = document.querySelector(".target-amount");

console.log(start);
console.log(buttonFirst);
console.log(buttonSecond);
console.log(depositBtn);
console.log(incomeFirst);
console.log(incomeSecond);
console.log(budgetDay);
console.log(expensesMonth);
console.log(addIncom);
console.log(addExpenses);
console.log(incomePeriod);
console.log(targetMonth);
console.log(range);
console.log(salary);
console.log(incomeTitle);
console.log(incomeAmount);
console.log(expensesTitle);
console.log(expensesAmount);
console.log(expensesItem);
console.log(mission);